version: "3"

services:
  minio:
    image: minio/minio:latest
    container_name: experiments_minio
    # restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ACCESS_KEY=12345678
      - MINIO_SECRET_KEY=password
      - CONSOLE_ACCESS_KEY=test
      - CONSOLE_SECRET_KEY=test
    command: server --address ":9000" --console-address ":9001" /data
    volumes:
      - minio_data:/data

volumes:
  minio_data:
    external: true